### ISSUE TITLE
Api routing for Post & Comment

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#2]
Those route are useless: `PUT /post/:id` and `PUT /comment/:id`  
Adding route to edit post and comment, that take a 'content' value: `PUT /post/:id/edit` `PUT /comment/:id/edit`.  
Adding route to like/unlike post and comment `PUT /[post | commment]/:id/[like | unlike]/:userID`.

**Comment by killian-mahe** [comment]
What the difference for you between `PUT /post/;id` and `Put /post/:id/edit` ?
Except the endpoint name, there is no difference as a PUT request is always considered as an update request on an API.

**Comment by killian-mahe** [comment]
All routes are construct on the sale pattern. All the variables needed in order to retrieve the model in the database are taking from the URL parameters, others (as the `:userID` here) are retrieve from the form the request's body.

**Comment by baanloh** [comment]
> 
> 
> What the difference for you between `PUT /post/:id` and `PUT /post/:id/edit` ?
> Except the endpoint name, there is no difference as a PUT request is always considered as an update request on an API. Therefore, there is no need to add an `edit` in the URL.

`PUT /post/:id` need the full post. But only content is editable. Request body must be change to take only `content` value.
