### ISSUE TITLE
Route to load Comments

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#26]
Need a route to load comments with paging. Something like `GET /comments/:postId`
and in the body :
```jsonc
{
   "from": 5, // index of the first comment to load
   "count": 10 // how many comment to load
}
```

Returns an array of comments.

**Comment by killian-mahe** [comment]
This is the result of `GET /comments/:postID` : 

`{
   "total": 50,
   "per_page": 15,
   "current_page": 1,
   "last_page": 4,
   "first_page_url": "http://laravel.app?page=1",
   "last_page_url": "http://laravel.app?page=4",
   "next_page_url": "http://laravel.app?page=2",
   "prev_page_url": null,
   "path": "http://laravel.app",
   "from": 1,
   "to": 15,
   "data":[
        {
            // Result Object
        },
        {
            // Result Object
        }
   ]
}`

**Comment by killian-mahe** [comment]
So you don't need any route patern. The API will give you the url.

**Comment by baanloh** [comment]
ok. btw, the api doc isn't up-to-date.

**Comment by killian-mahe** [comment]
Yes, because this comments and posts are not finished.
