### ISSUE TITLE
A route to check api_token

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#27]
Is there any route to check if a api_token is still valid ? (ie user still logged)

**Comment by killian-mahe** [comment]
No, but I don't know why you want this route ?

**Comment by baanloh** [comment]
to using Angular guard feature. That's basically a test to determine if a user can access to a specific route. I need it to make a "AuthGuard".

**Comment by killian-mahe** [comment]
Ok, let's create a route `POST /token`, that return a boolean.

**Comment by baanloh** [comment]
can you confirm :

body:
```json
api_token: "token"
```
response:
just a boolean or a json object ?

**Comment by killian-mahe** [comment]
The request is good, and the back return only a boolean, nothing else.
