### ISSUE TITLE
Idea : Api Permission

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#4]
To determins accessible files use a tag system: 
```jsonc
"accessible_files": {
  "tags": [ "", ""], // a list of user determined tags
  "files": [ 0, 0] // a list of file ids for specific access
}
```
Also add a list of tag to File, with the following route to add/remove: 
+ `PUT /file/:id/tag/:tag`
+ `REMOVE /file/:id/tag/:tag`

Add the list of tag on project, and route to add/remove them:
+ `PUT /project/:id/tag/:tag`
+ `REMOVE /project/:id/tag/:tag`

**Comment by killian-mahe** [comment]
Will be added in the future release !

**Comment by killian-mahe** [comment]
> To determins accessible files use a tag system:
> 
> ```js
> "accessible_files": {
>   "tags": [ "", ""], // a list of user determined tags
>   "files": [ 0, 0] // a list of file ids for specific access
> }
> ```
> 
> Also add a list of tag to File, with the following route to add/remove:
> 
> * `PUT /file/:id/tag/:tag`
> * `REMOVE /file/:id/tag/:tag`
> 
> Add the list of tag on project, and route to add/remove them:
> 
> * `PUT /project/:id/tag/:tag`
> * `REMOVE /project/:id/tag/:tag`

Routes for new tags on projects and files are `POST` requests, not `PUT`.
