### ISSUE TITLE
User data inconsistency

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#42]
The property `links` in the routes `GET` and `PUT` of `/user/{user_id}` dont have the same type in the doc.

- `GET` 
```jsonc
"links": [
    {
      "name": "string",
      "url": "string"
    }
  ],
```
- `PUT`
 ```jsonc
  "links": [
    "string"
  ],
```

**Comment by baanloh** [comment]
Same isssue with `GET` and `PUT` of `/project/{project_id}`

**Comment by killian-mahe** [comment]
The documentation has been updated.
