### ISSUE TITLE
Put routes, fail at data checking

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#49]
When I try to change user's data by passing non-changed data, it raise an error because of username and email are already taken by himself.

![image](https://user-images.githubusercontent.com/33934311/82676355-8dddf980-9c46-11ea-868d-86553cc67777.png)

**Comment by killian-mahe** [comment]
Well, it's a PUT method, so it assumes that the when you send data, you want to edit them.

So, for me, this error is a good thing.
