### ISSUE TITLE
PUT /user/:id invalid response

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#50]
Seem `PUT /user/:id` return a invalid json object, so it can't be parsed.

![image](https://user-images.githubusercontent.com/33934311/82678379-ce8b4200-9c49-11ea-9f23-918402b3cb5c.png)

**Comment by killian-mahe** [comment]
The request doesn't send any JSON object. As written in the doc, the API response with a 200 HTTP code.
