### ISSUE TITLE
Not all project id are return with user data

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#55]
`GET /user/:id` don't return all project ids.

### project_user
![image](https://user-images.githubusercontent.com/33934311/82825256-32607580-9eab-11ea-9c11-6389c2b8c350.png)

### returned data
![image](https://user-images.githubusercontent.com/33934311/82825281-3e4c3780-9eab-11ea-9c59-35ba063c5afb.png)

**Comment by killian-mahe** [comment]
How to reproduce ?

**Comment by killian-mahe** [comment]
Working when I try...
