### ISSUE TITLE
Api Project management routes

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#6]
`POST /project/:id/members/:userID` add member to project
`REMOVE /project/:id/members/:userID` remove member from project
`PUT /project/:id/permissions/:userID` set permission for member

**Comment by killian-mahe** [comment]
As I suggest in the #2 issue, the best way is to pass the `:userID` in the request's body.

**Comment by killian-mahe** [comment]
And I suppose it's not `post` but `project`. So I would say :
`POST /project/:id/members`
`DELETE /project/:id/members`
`PUT /project/:id/permissions`

**Comment by baanloh** [comment]
`DELETE` method cannot have a body.  
So, `DELETE /project/:id/members/:userID` ?

**Comment by killian-mahe** [comment]
Done in the next pull request
