### ISSUE TITLE
Add member forbidden as owner

### ISSUE THREAD

**Issue by baanloh** [shareYourProject/back-end#73]
Adding a member to a project as owner return `403 forbidden` response.

**Comment by baanloh** [comment]
Same error when I try to edit permissions.

**Comment by baanloh** [comment]
The `403 forbidden` occurs only when editing owner permission.

**Comment by killian-mahe** [comment]
You can't update the permissions of the owner. He has and will have all the permissions.

**Comment by killian-mahe** [comment]
That's why you get a `403 forbidden` error.

**Comment by baanloh** [comment]
Cannot add member as owner.
